import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// 1. 配置 App 的基础信息
export const metadata: Metadata = {
  title: "Pareto 80/20 Learner",
  description: "Generated by DeepSeek",
  manifest: "/manifest.json", // 关键：关联刚才创建的清单文件
  icons: {
    apple: "/icon.png", // iPhone 桌面图标
  },
};

// 2. 配置视口，禁止用户缩放，像原生 App 一样
export const viewport: Viewport = {
  themeColor: "#ffffff",
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN">
      <body className={inter.className}>{children}</body>
    </html>
  );
}